package com.dsw.guankong.dal.base;

import com.dsw.guankong.model.TpUserDo;
import com.dsw.guankong.model.TpUserDoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TpUserDoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_user
     *
     * @mbggenerated Sun Jan 07 13:10:30 CST 2018
     */
    int countByExample(TpUserDoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_user
     *
     * @mbggenerated Sun Jan 07 13:10:30 CST 2018
     */
    int deleteByExample(TpUserDoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_user
     *
     * @mbggenerated Sun Jan 07 13:10:30 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_user
     *
     * @mbggenerated Sun Jan 07 13:10:30 CST 2018
     */
    int insert(TpUserDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_user
     *
     * @mbggenerated Sun Jan 07 13:10:30 CST 2018
     */
    int insertSelective(TpUserDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_user
     *
     * @mbggenerated Sun Jan 07 13:10:30 CST 2018
     */
    List<TpUserDo> selectByExample(TpUserDoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_user
     *
     * @mbggenerated Sun Jan 07 13:10:30 CST 2018
     */
    TpUserDo selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_user
     *
     * @mbggenerated Sun Jan 07 13:10:30 CST 2018
     */
    int updateByExampleSelective(@Param("record") TpUserDo record, @Param("example") TpUserDoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_user
     *
     * @mbggenerated Sun Jan 07 13:10:30 CST 2018
     */
    int updateByExample(@Param("record") TpUserDo record, @Param("example") TpUserDoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_user
     *
     * @mbggenerated Sun Jan 07 13:10:30 CST 2018
     */
    int updateByPrimaryKeySelective(TpUserDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_user
     *
     * @mbggenerated Sun Jan 07 13:10:30 CST 2018
     */
    int updateByPrimaryKey(TpUserDo record);
}